# Generated by Django 4.0.2 on 2022-03-12 16:49

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.BigAutoField(auto_created=True,
                                           primary_key=True,
                                           serialize=False,
                                           verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('duration', models.IntegerField()),
                ('date', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'games',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False,
                                        primary_key=True, serialize=False)),
                ('login', models.CharField(max_length=64, unique=True)),
                ('name', models.CharField(max_length=64)),
                ('password', models.CharField(max_length=256)),
                ('email', models.EmailField(max_length=254)),
                ('piece', models.IntegerField()),
                ('avatar', models.URLField()),
            ],
            options={
                'db_table': 'users',
            },
        ),
        migrations.CreateModel(
            name='GameUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True,
                                           primary_key=True,
                                           serialize=False,
                                           verbose_name='ID')),
                ('rank', models.IntegerField()),
                ('money', models.IntegerField()),
                ('hotels', models.IntegerField()),
                ('houses', models.IntegerField()),
                ('host', models.BooleanField()),
                ('duration', models.IntegerField()),
                ('bot', models.BooleanField()),
                ('game', models.ForeignKey(on_delete=django.db.models
                                           .deletion.CASCADE,
                                           related_name='users_game',
                                           to='game_handler.game')),
                ('user', models.ForeignKey(null=True,
                                           on_delete=django.db.models
                                           .deletion.CASCADE,
                                           related_name='users_stats',
                                           to='game_handler.user')),
            ],
            options={
                'db_table': 'game_users',
            },
        ),
        migrations.CreateModel(
            name='UserFriend',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True,
                                           serialize=False,
                                           verbose_name='ID')),
                ('friend', models.ForeignKey(on_delete=django
                                             .db.models.deletion.CASCADE,
                                             related_name='friends_friend',
                                             to='game_handler.user')),
                ('user', models.ForeignKey(on_delete=django.db.models
                                           .deletion.CASCADE,
                                           related_name='friends_user',
                                           to='game_handler.user')),
            ],
            options={
                'db_table': 'user_friends',
                'unique_together': {('user', 'friend')},
            },
        ),
    ]
